def exception_handler(e):
    print(e.message)